# Generated by Django 6.0.5 on 2026-06-07 22:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名称', max_length=64, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(blank=True, default='#409EFF', help_text='标签颜色', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mkt_user_tags',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='优惠券名称', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('coupon_type', models.CharField(choices=[('fixed', '固定面额'), ('percent', '折扣券')], default='fixed', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('face_value', models.DecimalField(decimal_places=2, default=0, help_text='固定面额（元）', max_digits=12)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='折扣率，0.80 表示 8 折', max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='最低使用门槛（元）', max_digits=12)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='折扣券最大优惠金额', max_digits=12, null=True)),
                ('scope', models.CharField(choices=[('public', '公开领取'), ('directed', '定向发放')], default='directed', max_length=20)),
                ('total_quantity', models.IntegerField(default=0, help_text='发放总量，0 表示不限')),
                ('issued_count', models.IntegerField(default=0, help_text='已发放数量')),
                ('per_user_limit', models.IntegerField(default=1, help_text='每人限领数量')),
                ('valid_from', models.DateTimeField(help_text='生效开始时间')),
                ('valid_until', models.DateTimeField(help_text='过期时间')),
                ('audience_tag_ids', models.JSONField(blank=True, default=list, help_text='领取门槛：指定标签，空表示不限')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mkt_coupons',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='活动名称', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('promotion_type', models.CharField(choices=[('bonus', '满赠（充X送Y）'), ('discount', '满减（满A减B）'), ('tiered_cashback', '阶梯返现')], db_index=True, max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_time', models.DateTimeField(help_text='生效开始时间')),
                ('end_time', models.DateTimeField(help_text='生效结束时间')),
                ('audience_type', models.CharField(choices=[('all', '全部用户'), ('role', '指定角色'), ('tag', '指定标签')], default='all', max_length=20)),
                ('audience_roles', models.JSONField(blank=True, default=list, help_text='指定角色，如 ["student"]')),
                ('audience_tag_ids', models.JSONField(blank=True, default=list, help_text='指定标签ID列表')),
                ('limit_type', models.CharField(choices=[('none', '不限次'), ('per_day', '每人每日限享'), ('total', '每人累计限享')], default='none', max_length=20)),
                ('limit_count', models.IntegerField(default=0, help_text='限享次数，0 表示不限制')),
                ('stacking_policy', models.CharField(choices=[('allow', '活动+优惠券可叠加'), ('exclusive', '互斥（用了活动不能用券，反之亦然）'), ('coupon_only', '仅允许用券，活动不生效'), ('promo_only', '仅允许活动，优惠券不生效')], default='allow', help_text='叠加策略', max_length=30)),
                ('rule_config', models.JSONField(default=dict, help_text='活动规则：满赠={threshold, bonus}, 满减={threshold, discount}, 阶梯返现={tiers: [{threshold, rate}]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mkt_promotions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('benefit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='优惠/赠送金额', max_digits=12)),
                ('redemption_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='marketing.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mkt_promotion_redemptions',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['promotion', 'user', 'redemption_date'], name='mkt_pr_promo_user_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', '可用'), ('used', '已用'), ('expired', '已过期'), ('revoked', '已回收')], db_index=True, default='available', max_length=20)),
                ('code', models.CharField(help_text='券码', max_length=40, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='实际核销优惠金额（核销时填入）', max_digits=12)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_order_no', models.CharField(blank=True, default='', max_length=40)),
                ('expired_at', models.DateTimeField(help_text='实际过期时间（冗余自 coupon.valid_until，便于单独续期）')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=255)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='marketing.coupon')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_coupons', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mkt_user_coupons',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', 'status'], name='mkt_uc_user_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='marketing.usertag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mkt_user_tag_relations',
                'constraints': [models.UniqueConstraint(fields=('user', 'tag'), name='uniq_user_tag')],
            },
        ),
    ]
