# Generated by Django 6.0.5 on 2026-06-07 22:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_consumption_room_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='balancechangelog',
            new_name='bcl_user_settlement_period_idx',
            old_name='balance_change_user_settle_6b2e54_idx',
        ),
        migrations.RenameIndex(
            model_name='consumptionrecord',
            new_name='consump_cat_created_idx',
            old_name='consumption_cat_created_9e3b62_idx',
        ),
        migrations.RenameIndex(
            model_name='consumptionrecord',
            new_name='consump_chn_created_idx',
            old_name='consumption_channel_created_1f0c7a_idx',
        ),
        migrations.RenameIndex(
            model_name='consumptionrecord',
            new_name='consump_user_cat_idx',
            old_name='consumption_user_cat_5a2b91_idx',
        ),
        migrations.AddField(
            model_name='rechargeorder',
            name='applied_promotions',
            field=models.JSONField(blank=True, default=list, help_text='命中的营销活动明细 [{promotion_id, name, type, benefit_amount}]'),
        ),
        migrations.AddField(
            model_name='rechargeorder',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='活动赠送金额', max_digits=12),
        ),
        migrations.AddField(
            model_name='rechargeorder',
            name='coupon_id',
            field=models.IntegerField(blank=True, help_text='选择的用户优惠券ID', null=True),
        ),
        migrations.AddField(
            model_name='rechargeorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='优惠券优惠金额', max_digits=12),
        ),
        migrations.AddField(
            model_name='rechargeorder',
            name='final_credited',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='最终到账金额（amount + bonus_amount - discount_amount 按规则落地）', max_digits=12),
        ),
        migrations.AddField(
            model_name='rechargeorder',
            name='final_payable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='学生实付金额（冗余，便于展示）', max_digits=12),
        ),
        migrations.AddField(
            model_name='rechargeorder',
            name='stacking_policy',
            field=models.CharField(blank=True, default='', help_text='实际采用的叠加策略快照', max_length=30),
        ),
    ]
