# Generated by Django 6.0.5 on 2026-06-07 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_rename_balance_change_user_settle_6b2e54_idx_bcl_user_settlement_period_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='计划名称', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='每次充值金额', max_digits=12)),
                ('period', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], help_text='扣款周期', max_length=20)),
                ('channel', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bank', '银行卡')], help_text='充值渠道', max_length=20)),
                ('start_date', models.DateField(help_text='开始日期')),
                ('end_date', models.DateField(help_text='结束日期')),
                ('next_execution_date', models.DateField(db_index=True, help_text='下次执行日期')),
                ('last_execution_date', models.DateField(blank=True, help_text='上次执行日期', null=True)),
                ('total_executions', models.IntegerField(default=0, help_text='已执行次数')),
                ('success_count', models.IntegerField(default=0, help_text='成功次数')),
                ('failure_count', models.IntegerField(default=0, help_text='失败次数')),
                ('status', models.CharField(choices=[('active', '执行中'), ('paused', '已暂停'), ('ended', '已结束'), ('expired', '已过期')], db_index=True, default='active', max_length=20)),
                ('failure_action', models.CharField(choices=[('skip', '跳过本次继续执行'), ('pause', '暂停计划等待处理')], default='skip', help_text='失败时处理策略', max_length=20)),
                ('created_by', models.CharField(default='student', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recharge_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(db_index=True, help_text='计划执行日期')),
                ('executed_at', models.DateTimeField(blank=True, help_text='实际执行时间', null=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('success', '执行成功'), ('failed', '执行失败'), ('skipped', '已跳过')], db_index=True, default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='本次充值金额', max_digits=12)),
                ('channel', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bank', '银行卡')], max_length=20)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, help_text='关联的充值订单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_execution', to='billing.rechargeorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_executions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='billing.rechargeplan')),
            ],
            options={
                'db_table': 'plan_executions',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rechargeplan',
            index=models.Index(fields=['user', 'status'], name='plan_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rechargeplan',
            index=models.Index(fields=['status', 'next_execution_date'], name='plan_status_next_idx'),
        ),
        migrations.AddIndex(
            model_name='planexecution',
            index=models.Index(fields=['plan', 'scheduled_date'], name='exec_plan_date_idx'),
        ),
        migrations.AddIndex(
            model_name='planexecution',
            index=models.Index(fields=['user', 'status'], name='exec_user_status_idx'),
        ),
    ]
