# Generated by Django 6.0.5 on 2026-06-07 23:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_rechargeplan_planexecution_and_more'),
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionrecord',
            name='billing_detail',
            field=models.JSONField(blank=True, default=dict, help_text='计费明细：包含命中策略名、分段/时段构成等'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='单价（保留字段，实际以 billing_detail 为准）', max_digits=12),
        ),
        migrations.CreateModel(
            name='PriceStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='策略名称')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='策略描述')),
                ('strategy_type', models.CharField(choices=[('fixed', '固定单价'), ('tiered', '阶梯单价'), ('timeslot', '时段单价')], max_length=20, verbose_name='策略类型')),
                ('category', models.CharField(choices=[('water', '水费'), ('electricity', '电费')], max_length=20, verbose_name='适用类目')),
                ('scope_type', models.CharField(choices=[('global', '全校默认'), ('campus', '校区'), ('building', '楼栋'), ('room', '房间')], default='global', max_length=20, verbose_name='生效维度')),
                ('effective_from', models.DateField(verbose_name='生效开始日期')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='生效结束日期（空表示长期）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, help_text='数值越大优先级越高，同维度取优先级最高的策略')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_strategies', to='housing.building', verbose_name='楼栋')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_strategies', to='housing.campus', verbose_name='校区')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_strategies', to='housing.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '价格策略',
                'verbose_name_plural': '价格策略',
                'db_table': 'price_strategies',
                'ordering': ['-priority', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_usage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='起始用量（含）')),
                ('max_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='结束用量（不含，空表示不限）')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='本档单价')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='billing.pricestrategy', verbose_name='所属策略')),
            ],
            options={
                'verbose_name': '阶梯单价分段',
                'verbose_name_plural': '阶梯单价分段',
                'db_table': 'price_tiers',
                'ordering': ['sort_order', 'min_usage'],
            },
        ),
        migrations.CreateModel(
            name='PriceTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='时段名称，如峰、平、谷')),
                ('weekday_mask', models.CharField(default='1111111', help_text='7 位二进制，周一到周日，1 表示适用', max_length=7)),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='此时段单价')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='billing.pricestrategy', verbose_name='所属策略')),
            ],
            options={
                'verbose_name': '时段单价配置',
                'verbose_name_plural': '时段单价配置',
                'db_table': 'price_timeslots',
                'ordering': ['sort_order', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='pricestrategy',
            index=models.Index(fields=['category', 'scope_type', 'is_active'], name='price_strat_categor_88ebff_idx'),
        ),
        migrations.AddIndex(
            model_name='pricestrategy',
            index=models.Index(fields=['campus_id', 'category', 'is_active'], name='price_strat_campus__2161b9_idx'),
        ),
        migrations.AddIndex(
            model_name='pricestrategy',
            index=models.Index(fields=['building_id', 'category', 'is_active'], name='price_strat_buildin_bd57ee_idx'),
        ),
        migrations.AddIndex(
            model_name='pricestrategy',
            index=models.Index(fields=['room_id', 'category', 'is_active'], name='price_strat_room_id_29705f_idx'),
        ),
    ]
