# Generated by Django 6.0.5 on 2026-06-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_seed_default_message_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagedeliverylog',
            new_name='msgdlv_created_at_idx',
            old_name='message_del_created_914234_idx',
        ),
        migrations.RenameIndex(
            model_name='messagedeliverylog',
            new_name='msgdlv_status_channel_idx',
            old_name='message_del_status__7fbd4a_idx',
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='variables_schema',
            field=models.JSONField(blank=True, default=dict, help_text='变量说明 JSON，如 {"order_no": "订单号", "amount": "金额"}'),
        ),
    ]
