# Generated by Django 6.0.5 on 2026-06-07 23:47

from django.conf import settings
from django.db import migrations, models


def set_existing_announcements_published(apps, schema_editor):
    Announcement = apps.get_model('notices', 'Announcement')
    Announcement.objects.filter(published=False).update(published=True)


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_rename_message_del_created_914234_idx_msgdlv_created_at_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='失效时间，为空表示永不失效', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='published',
            field=models.BooleanField(default=False, help_text='是否已实际推送过'),
        ),
        migrations.RunPython(
            set_existing_announcements_published,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='定时发布时间，为空表示立即发布', null=True),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['published', 'scheduled_at'], name='ann_pub_scheduled_idx'),
        ),
    ]
